import NavBar from "./components/NavBar";
export const metadata = {
  title: "Tutor LPT",
  description: "Generated by N./src/app/providers",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
